version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=memovalverd
      - POSTGRES_PASSWORD=Memo#4284
      - POSTGRES_DB=devwanabi_db
    ports:
      - '5432:5432'
    volumes:
      - ./db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge

#volumes:
 # db:
   #driver: local
