# Generated by Django 5.0.2 on 2024-03-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
