# Generated by Django 5.0.2 on 2024-03-02 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
