# Generated by Django 5.0.2 on 2024-03-16 23:58

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content2',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
